[2022-06-20 08:33:36,673] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: scenario_insert_only.run_this manual__2022-06-20T08:33:35.866848+00:00 [queued]>
[2022-06-20 08:33:36,688] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: scenario_insert_only.run_this manual__2022-06-20T08:33:35.866848+00:00 [queued]>
[2022-06-20 08:33:36,689] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 08:33:36,690] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 08:33:36,691] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 08:33:36,712] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_this> on 2022-06-20 08:33:35.866848+00:00
[2022-06-20 08:33:36,720] {standard_task_runner.py:52} INFO - Started process 806 to run task
[2022-06-20 08:33:36,724] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'scenario_insert_only', 'run_this', 'manual__2022-06-20T08:33:35.866848+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/scenario_insert_only.py', '--cfg-path', '/tmp/tmpe16zjf_v', '--error-file', '/tmp/tmpjq6gd4y3']
[2022-06-20 08:33:36,725] {standard_task_runner.py:80} INFO - Job 16: Subtask run_this
[2022-06-20 08:33:36,797] {task_command.py:370} INFO - Running <TaskInstance: scenario_insert_only.run_this manual__2022-06-20T08:33:35.866848+00:00 [running]> on host d7f065c79af8
[2022-06-20 08:33:36,883] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=scenario_insert_only
AIRFLOW_CTX_TASK_ID=run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T08:33:35.866848+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-20T08:33:35.866848+00:00
[2022-06-20 08:33:36,886] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-20 08:33:36,888] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/***/dags/script/transfer_case_insert_only.py']
[2022-06-20 08:33:36,900] {subprocess.py:85} INFO - Output:
[2022-06-20 08:33:37,202] {subprocess.py:92} INFO - =>table transactions in database y successful
[2022-06-20 08:33:37,206] {subprocess.py:92} INFO - database X:
[2022-06-20 08:33:37,209] {subprocess.py:92} INFO - The number of parts:  4
[2022-06-20 08:33:37,213] {subprocess.py:92} INFO - [('2022-06-11', 1000), ('2022-06-12', 2000), ('2022-06-13', 3000), ('2022-06-14', 6000)]
[2022-06-20 08:33:37,217] {subprocess.py:92} INFO - insert data:  ('2022-06-11', 1000)
[2022-06-20 08:33:37,219] {subprocess.py:92} INFO - insert data:  ('2022-06-12', 2000)
[2022-06-20 08:33:37,222] {subprocess.py:92} INFO - insert data:  ('2022-06-13', 3000)
[2022-06-20 08:33:37,223] {subprocess.py:92} INFO - insert data:  ('2022-06-14', 6000)
[2022-06-20 08:33:37,226] {subprocess.py:92} INFO - insert list transaction successful
[2022-06-20 08:33:37,229] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-20 08:33:37,316] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=scenario_insert_only, task_id=run_this, execution_date=20220620T083335, start_date=20220620T083336, end_date=20220620T083337
[2022-06-20 08:33:37,384] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-20 08:33:37,447] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
